package com.example.pion.family.tracker.demo.domain.tracking

import com.example.pion.family.tracker.demo.domain.model.Zone
import kotlin.math.cos
import kotlin.math.sqrt

/**
 * One synthetic GPS fix generated by [RouteBlueprint.build] — LLM.md §8.4, PRD §3.5/US-33.
 * [offsetMs] is milliseconds since the simulation started; [SimulatedLocationSource] (`:data`,
 * phase-09 Implementation Step 3) schedules emission by it with `delay`, and stamps
 * `recordedAt = simulationStart + offsetMs` so filter/speed math sees consistent timestamps
 * (Key Insight #5 — never fake `recordedAt` to "look slower", `RouteStats` would then report a
 * nonsense duration for the trip).
 */
data class SimulatedFix(
    val latitude: Double,
    val longitude: Double,
    val offsetMs: Long,
)

/**
 * Pure function building a straight line that cuts through [zone] — PRD §3.5, phase-09
 * Implementation Step 1. The line runs from [SIMULATION_BUFFER_M] beyond the zone's edge on one
 * side, through the center, to [SIMULATION_BUFFER_M] beyond the edge on the opposite side, along
 * the axis from [zone]'s center toward the device's current position (or due north if the device
 * is already standing at the center — Key Insight #3). [SIMULATION_BUFFER_M] (150m) is
 * deliberately greater than [TrackingConstants.ZONE_EXIT_BUFFER_M] (30m) so the route always
 * clears both the entry radius and the exit hysteresis buffer, guaranteeing exactly one ENTER and
 * one EXIT (Risk Assessment: "`MIN_DISTANCE_M` loại bớt điểm mô phỏng khiến ENTER hoặc EXIT không
 * bắn").
 *
 * No Android import — plain Kotlin, testable with JUnit alone (LLM.md §8.2, same rule as every
 * other file in `domain/tracking/`). Uses a flat equirectangular approximation (meters-per-degree)
 * rather than [GeoDistance]'s full Haversine great-circle inverse problem — accurate enough at the
 * scale a zone radius allows (`ZONE_RADIUS_MAX_M` = 2000m, PRD §6) and far simpler for a demo-only
 * feature (YAGNI).
 *
 * **Known limitation, not fixed here:** for a very large zone (radius approaching
 * [TrackingConstants.ZONE_RADIUS_MAX_M] = 2000m), the fixed `pointCount`/`totalMillis` defaults
 * push the implied speed between consecutive fixes past [TrackingConstants.MAX_SPEED_KMH] (200),
 * so [LocationFilter] legitimately drops some of them — see `RouteBlueprintTest`'s
 * "known limitation" test, which pins this down instead of hiding it. Demo zones created through
 * the phase-06 editor default to [TrackingConstants.ZONE_RADIUS_DEFAULT_M] (150m), far under the
 * ~683m breakeven radius, so this does not affect the shipped demo data — flagged for phase-11/BA
 * if a future zone is deliberately created near the 2000m ceiling.
 */
object RouteBlueprint {
    const val DEFAULT_POINT_COUNT: Int = 20
    const val DEFAULT_TOTAL_MILLIS: Long = 30_000L

    /** > [TrackingConstants.ZONE_EXIT_BUFFER_M] (30m) — phase-09 Key Insight #3. */
    internal const val SIMULATION_BUFFER_M: Double = 150.0

    private const val METERS_PER_DEGREE_LAT: Double = 111_320.0
    private const val MIN_NORM_METERS: Double = 0.01
    private val NORTH = 1.0 to 0.0

    fun build(
        currentLat: Double,
        currentLng: Double,
        zone: Zone,
        pointCount: Int = DEFAULT_POINT_COUNT,
        totalMillis: Long = DEFAULT_TOTAL_MILLIS,
    ): List<SimulatedFix> {
        require(pointCount >= 2) { "pointCount must be at least 2 to draw a line" }

        val metersPerDegreeLng = METERS_PER_DEGREE_LAT * cos(Math.toRadians(zone.latitude))
        val (dirLat, dirLng) = directionUnitVector(
            fromLat = currentLat,
            fromLng = currentLng,
            toLat = zone.latitude,
            toLng = zone.longitude,
            metersPerDegreeLng = metersPerDegreeLng,
        )
        val distance = SIMULATION_BUFFER_M + zone.radiusMeters.toDouble()

        // "từ (tâm + hướng × (R+150m)) qua tâm tới (tâm − hướng × (R+150m))" — Implementation Step 1.
        val startLat = zone.latitude + dirLat * distance / METERS_PER_DEGREE_LAT
        val startLng = zone.longitude + dirLng * distance / metersPerDegreeLng
        val endLat = zone.latitude - dirLat * distance / METERS_PER_DEGREE_LAT
        val endLng = zone.longitude - dirLng * distance / metersPerDegreeLng

        return (0 until pointCount).map { index ->
            val t = index.toDouble() / (pointCount - 1)
            SimulatedFix(
                latitude = startLat + (endLat - startLat) * t,
                longitude = startLng + (endLng - startLng) * t,
                offsetMs = (totalMillis * t).toLong(),
            )
        }
    }

    /**
     * Unit vector (lat, lng components — meters-space, NOT degrees) from (fromLat,fromLng) to
     * (toLat,toLng). Falls back to due north ((1.0, 0.0)) when the two points coincide, per Key
     * Insight #3.
     */
    private fun directionUnitVector(
        fromLat: Double,
        fromLng: Double,
        toLat: Double,
        toLng: Double,
        metersPerDegreeLng: Double,
    ): Pair<Double, Double> {
        val dyMeters = (toLat - fromLat) * METERS_PER_DEGREE_LAT
        val dxMeters = (toLng - fromLng) * metersPerDegreeLng
        val norm = sqrt(dyMeters * dyMeters + dxMeters * dxMeters)
        return if (norm < MIN_NORM_METERS) NORTH else (dyMeters / norm) to (dxMeters / norm)
    }
}
